version: '3.8'
services:
  db:
    image: postgres
    container_name: pg_pickly
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$USER/docker_pg_data:/var/lib/postgresql/data
  app:
    image: microservice-template:latest
    container_name: microservice-template
    network_mode: host
    env_file:
      - .development.env
    volumes:
      - /pickly-backend-template:$PWD/pickly-backend-template
