version: "3.9"
services:
  posts:
    image: "m3ntorshipci/pickly:04"
    command: node dist/src/main.js
    environment:
      APP_NAME: posts-local
      PORT: 3000
      POSTS_URL: http://localhost:3000
      NOTIFICATIONS_URL: http://localhost:3001
      VOTES_URL: http://localhost:3004
    network_mode: host
  notifications:
    image: "m3ntorshipci/pickly:04"
    command: node dist/src/main.js
    environment:
      APP_NAME: notifications-local
      PORT: 3001
      POSTS_URL: http://localhost:3000
      NOTIFICATIONS_URL: http://localhost:3001
      VOTES_URL: http://localhost:3004
    network_mode: host
  votes:
    image: "m3ntorshipci/pickly:04"
    command: node dist/src/main.js
    environment:
      APP_NAME: votes-local
      PORT: 3004
      POSTS_URL: http://localhost:3000
      NOTIFICATIONS_URL: http://localhost:3001
      VOTES_URL: http://localhost:3004
    network_mode: host
