version: '3.8'
services:
  db:
    image: postgres
    container_name: pg_pickly
    network_mode: host
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/$PWD/docker_pg_data:/var/lib/postgresql/data
