swagger: "2.0"
info:
  version: "1.0.0"
  title: "Example API"
host: "mock-service.ahmedayoub.me"
tags:
- name: health
paths:
  /health:
    get:
      tags:
        - "health"
      summary: Health check
      operationId: healthCheck
      responses:
        200:
          description: Health check
          schema:
            type: object
            properties:
              status:
                type: boolean
                example: true

