name: echo

on:
  push:
    branches:
      - deployment

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.prepare.outputs.sha }}
      version: ${{ steps.prepare.outputs.version }}
      image: m3ntorshipci/pickly
      dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - id: prepare
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=version::$(git rev-parse --short=4 HEAD)"
  ensure:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - id: sha
        name: sha
        run: echo "sha ${{needs.prepare.outputs.sha}}"
      - run: echo "version ${{needs.prepare.outputs.version}}"
      - run: echo "image ${{needs.prepare.outputs.image}}"
      - run: echo "dockerfile ${{needs.prepare.outputs.dockerfile}}"
  build-and-push-app:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - id: install-dependencies
        run: yarn

      - id: run-unit-tests
        run: yarn test

      - id: build-app
        run: yarn build
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{needs.prepare.outputs.image}}
          dockerfile: ${{needs.prepare.outputs.dockerfile}}
          tags: ${{needs.prepare.outputs.version}}
  deploy:
    needs:
      - prepare
      - build-and-push-app

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v1

      - name: Kubectl configuration
        shell: bash
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DEV }}" | base64 -d -i > ~/.kube/config

      - name: install moustache
        run: |
          curl -sSL https://git.io/get-mo -o mo
          chmod +x mo
          sudo mv mo /usr/local/bin/
          echo "works" | mo

      # deploy dev
      - name: deploy-dev
        env:
          M3_VERSION: ${{needs.prepare.outputs.version}}
          M3_DEPLOYMENT_PATH: deploy/dev/fullstack
          TEMP_DIR: temp
          M3_NAMESPACE: m3ntorshipcom-dev
          M3_PROJECT: m3ntorshipcom
          M3_COMPONENET: fullstack
          M3_ENVIRONMENT: dev
          M3_REPLICAS: '1'
          M3_PORT_FRONTEND: '3000'
          M3_PORT_BACKEND: '1337'
          M3_SHA: ${{needs.prepare.outputs.sha}}
        # run: |
        #   echo $M3_VERSION
        #   mkdir -p $TEMP_DIR
        #   for f in $M3_DEPLOYMENT_PATH/apply/*; do mo -u "$f" > $TEMP_DIR/"$(basename $f)"; done
        #   kubectl apply -f $TEMP_DIR
        run: |
          echo $M3_VERSION
          mkdir -p $TEMP_DIR
          mo -u deploy/temp.yaml > $TEMP_DIR/temp.yaml
          kubectl apply -f $TEMP_DIR
