name: echo

on:
  push:
    branches:
      - deployment

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.prepare.outputs.sha }}
      version: ${{ steps.prepare.outputs.version }}
      image: m3ntorshipci/pickly
      dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v2
      - id: prepare
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=version::$(git rev-parse --short=4 HEAD)"
  ensure:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - id: sha
        name: sha
        run: echo "sha ${{needs.prepare.outputs.sha}}"
      - run: echo "version ${{needs.prepare.outputs.version}}"
      - run: echo "image ${{needs.prepare.outputs.image}}"
      - run: echo "dockerfile ${{needs.prepare.outputs.dockerfile}}"
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - id: install-dependencies
        run: yarn

      - id: run-unit-tests
        run: yarn test
