on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
      - edited

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: output sha
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: output version
        id: version
        run: echo "::set-output name=version::$(git rev-parse --short=4 HEAD)"

    outputs:
      sha: ${{steps.sha.outputs.sha}}
      version: ${{steps.version.outputs.version}}

  check-outputs:
    needs:
      - prepare
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "sha ${{ needs.prepare.outputs.sha }}"
          echo "version ${{ needs.prepare.outputs.version }}"

  build-and-push-image:
    needs:
      - prepare

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependancties
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build app
        run: yarn build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: m3ntorshipci/pickify-posts:${{ needs.prepare.outputs.version }}
          file: Dockerfile
